# Generated by Django 4.2.3 on 2023-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('price', models.IntegerField(max_length=6)),
            ],
        ),
    ]
